# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Release

on:
  workflow_dispatch
  # push:
  #   tags:
  #     - '*'

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'   
        cache-dependency-path: |
          'requirements/requirements.txt'
          'requirements/requirements_tests.txt'

    # - name: Install dependencies      
    #   run: |
    #     python --version
    #     python -m pip install --upgrade pip        
    #     # Install our package to make sure our setup works...
    #     pip install -U pip setuptools wheel
    #     pip install -r requirements/requirements.txt
    #     # set up all spacy language models that are used in our pytest tests
    #     python -m spacy download de_core_news_sm
    #     python -m spacy download en_core_web_sm
    #     python -m spacy download en_core_web_md
    #     # multilingual models for testing compatibility
    #     python -m spacy download es_core_news_sm
    #     python -m spacy download pl_core_news_sm
    #     python -m spacy download de_core_news_sm
    #     python -m spacy download xx_ent_wiki_sm
    #     # install scispacy model as well to ensure compatibility
    #     # we want to test execution of jupyter notebooks in pytest as well
    #     # Move previous multiple lines into single txt file
    #     pip install -r requirements/requirements_tests.txt

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16.5
      env:
        # TODO: Build Cython with the compile-all flag?
        # Unfortunately, there is no way to modify cibuildwheel's build command
        # so there is no way to pass this in directly.
        # This would require modifying cython's setup.py to look for these flags
        # in env vars.
        CIBW_BEFORE_BUILD: "pip install -r requirements/requirements.txt && python -m spacy download en_core_web_sm && python -m spacy download en_core_web_md"
        # CIBW_BEFORE_BUILD: "python setup.py build_ext --inplace"
        CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
        CIBW_ENVIRONMENT: CFLAGS='-O3 -g0 -mtune=generic -pipe -fPIC' LDFLAGS='-fPIC'          
        CIBW_TEST_COMMAND: pytest -k "not test_span_groups and not test_overlapping_spans and not test_multiword_span" {package}/tests && pytest -k "test_span_groups or test_overlapping_spans or test_multiword_span" {package}/tests

    - name: Check built
      run: ls dist

    - name: Get tag version
      id: get_tag_version
      run: echo ${{ steps.get_tag_version.outputs.TAG_VERSION }}

    # - name: Test with pytest
    #   run: |
    #     # run everything besides the QuickUMLS span group tests...
    #     pytest -k "not test_span_groups and not test_overlapping_spans and not test_multiword_span"
    #     # now in a separate session we can run the QuickUMLS span group tests...
    #     pytest -k "test_span_groups or test_overlapping_spans or test_multiword_span"      
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag_version.outputs.tag_version }}
        release_name: "Release v${{ steps.get_tag_version.outputs.tag_version }}"
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/*.tar.gz
        asset_name: ${{ steps.get_tag_version.outputs.tag_version }}.tar.gz
        asset_content_type: application/zip
