name: test_conditions

on:
    workflow_dispatch:
        inputs:
            install_prerelease:
                description: 'Check this to install the prerelease version of medspacy if available and the version is newer than formal release.'  
                type: boolean   
                required: false
                default: false

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.event.inputs.install_prerelease }} == false"
              if: ${{ github.event.inputs.install_prerelease }} == false
            - run: echo "${{ github.event.inputs.install_prerelease }} == true"
              if: ${{ github.event.inputs.install_prerelease }} == true
            - run: echo "${{ github.event.inputs.install_prerelease }}"
              if: ${{ github.event.inputs.install_prerelease }} 
            - run: echo "not ${{ github.event.inputs.install_prerelease }}"
              if: not ${{ github.event.inputs.install_prerelease }}
            - run: echo "${{ github.event.inputs.install_prerelease }} == 'false'"
              if: ${{ github.event.inputs.install_prerelease == 'false' }} 
            - run: echo "${{ github.event.inputs.install_prerelease }} == 'true'"
              if: ${{ github.event.inputs.install_prerelease  == 'true' }}
            - run: echo "true"
              if: true
            - run: echo "false"
              if: false
